project_id: '420534'
api_token_env: 'DERIV_COM_CROWDIN_API_KEY'
preserve_hierarchy: true

files:
    - source: /crowdin/messages.json
      translation: /src/translations/%two_letters_code%.json
      languages_mapping:
          two_letters_code:
              zh-CN: zh_cn
              zh-TW: zh_tw
