export const app_name = 'derivcrypto'
export const app_url = 'derivcrypto.com'
export const deriv_app_crypto_url = 'app.derivcrypto.com'
export const deriv_app_url = 'app.deriv.com'
export const deriv_com_url = 'deriv.com'
